### ISSUE TITLE
auto-restore not working

### ISSUE THREAD

**Issue by sleffler** [vapier/chrome-ext-tabs-backup#1]
chome:://version: 120.0.6099.235 (Official Build) (64-bit) 

auto-restore of  any saved tab set appears to do nothing. I can use the "Advanced Restore" ui and select all the windows in a tab set to get windows restored. Happens every time.

**Comment by vapier** [comment]
what are you calling "auto-restore" ?  when you click the extension popup, then the "restore" button for a specific session ?  or something else ?

**Comment by sleffler** [comment]
Correct. See attached screenshot.

**Comment by vapier** [comment]
there wasn't an attachment, but i found the bug either way
