### ISSUE TITLE
Where is the backup location?

### ISSUE THREAD

**Issue by djay07** [vapier/chrome-ext-tabs-backup#3]
Where is the backup location? - Backup location is not to be found.
It would help to have it as a setting.

**Comment by vapier** [comment]
it's using standard [Chrome local storage](https://developer.chrome.com/docs/extensions/reference/api/storage).  what exactly are you trying to do ?  what setting are you talking about ?

**Comment by djay07** [comment]
Trying to move the backup to a different device. But the data is nowhere to be found.

**Comment by vapier** [comment]
there is no export option, and the current design does not sync tabs between devices.  I don't see that changing as it's not the intention/scope of the extension.

I imagine there are others in the CWS that would do what you want already.  or you can use Chrome's builtin "Tabs from other devices" (chrome://history/syncedTabs) functionality to open existing windows on a new system.

**Comment by djay07** [comment]
Too bad. 
Then I don't get the point of you mentioning it can do backups.
Thanks for clarifying.

**Comment by vapier** [comment]
the "backups" are per-device checkpoints to be resilient to Chrome crashes where it forgets all of your open windows/tabs.  while Chrome is often pretty good about restoring tabs on crash, it isn't perfect, and diff releases can be more stable in this regard than others.

it isn't a long term or a cross-device backup system.
